add host precheck and more accurate reporting

diff --git a/Ansible/roles/marvin/templates/smoketests.sh.j2 b/Ansible/roles/marvin/templates/smoketests.sh.j2
--- a/Ansible/roles/marvin/templates/smoketests.sh.j2
+++ b/Ansible/roles/marvin/templates/smoketests.sh.j2
@@ -58,6 +58,32 @@ cleanup() {
         cloudmonkey delete alerts ids=$id || true
     done
 }
+ 
+hosts_precheck() {
+  cloudmonkey set asyncblock false
+  cloudmonkey set display json
+  HOSTS_NOT_UP=`cloudmonkey list hosts type=routing filter='name,state' | jq '.host[] | select(.state != "Up")'`
+  if [ -n $HOSTS_NOT_UP ]; then
+    sleep 120
+    HOSTS_NOT_UP=`cloudmonkey list hosts type=routing filter='name,state' | jq '.host[] | select(.state != "Up")'`
+    if [ -n $HOSTS_NOT_UP ]; then
+      MGMT_SERV_IP={{ hostvars[groups['primary_cs_manager'][0]]['ansible_ssh_host'] }}
+      ROOT_SK={{ cm_secretkey }}
+      ROOT_AK={{ cm_apikey }}
+      for HYP_HOST in $HOSTS_NOT_UP; do
+        HOST_UUID=`cloudmonkey list hosts filter=uuid type=routing name=$HYP_HOST`
+        cloudmonkey configure outofbandmanagement driver="nested-cloudstack" address=$MGMT_SERV_IP username=$ROOT_AK password=$ROOT_SK port=$HOST_UUID
+        cloudmonkey issue outofbandmanagementpoweraction action="RESET" hostid=$HOST_UUID timeout=180
+     done
+    HOSTS_NOT_UP=`cloudmonkey list hosts type=routing filter='name,state' | jq '.host[] | select(.state != "Up")'`
+    if [ -n $HOSTS_NOT_UP ]; then
+      sleep 120
+      HOSTS_NOT_UP=`cloudmonkey list hosts type=routing filter='name,state' | jq '.host[] | select(.state != "Up")'`
+      echo "Cannot get all hosts into 'Up' state. bailing out"
+      exit 1
+    fi
+  fi
+}
 
 runtest() {
     file=$1
@@ -89,10 +115,44 @@ slackmsg() {
   --title-link "$jenkinslink"
 }
 
+determine_last_test_outcome() {
+  LASTUPDATEDIR=`ls $LOGDIR/*/ -td | head -n 1`
+  if [[ -n `cat ${LASTUPDATEDIR}results.txt| grep 'Ran 0 tests'` ]]; then
+    NOTRUN_SKIPPED=$((NOTRUN_SKIPPED+1))
+    echo "test $(basename $file) in {{ env_name_clean }} skipped or failed to run"
+{% if use_hipchat %}    hipchat --action sendNotification --room "Marvin Notifications" --messageFormat "html" --colour "gray" --message "test $TESTFILENAME in {{ env_name_clean }} looks to have <span style="color:#FF0000">errors</span>. Currently; $PASSES passes, $FAILS fails and $NOTRUN_SKIPPED not run.<br>Tests have taken $all_tests_elapsed hours so far. $tests_left tests to go."
+{% endif %}
+{% if use_slack %}    slackmsg "Test $TESTFILENAME looks to have *errors*.\nCurrently; $PASSES passes, $FAILS fails and $NOTRUN_SKIPPED not run.\nTests have taken $all_tests_elapsed hours so far. $tests_left tests to go." "warning"
+{% endif %}
+  else
+    if [[ -s ${LASTUPDATEDIR}failed_plus_exceptions.txt ]]; then
+      FAILS=$((FAILS+1))
+      echo "test $(basename $file) in {{ env_name_clean }} looks to have errors"
+{% if use_hipchat %}      hipchat --action sendNotification --room "Marvin Notifications" --messageFormat "html" --colour "gray" --message "test $TESTFILENAME in {{ env_name_clean }} looks to have <span style="color:#FF0000">errors</span>. Currently; $PASSES passes, $FAILS fails and $NOTRUN_SKIPPED not run.<br>Tests have taken $all_tests_elapsed hours so far. $tests_left tests to go."
+{% endif %}
+{% if use_slack %}      slackmsg "Test $TESTFILENAME looks to have *errors*.\nCurrently; $PASSES passes, $FAILS fails and $NOTRUN_SKIPPED not run.\nTests have taken $all_tests_elapsed hours so far. $tests_left tests to go." "warning"
+{% endif %}
+    else
+      PASSES=$((PASSES+1))
+      echo "test $TESTFILENAME in {{ env_name_clean }} looks OK"
+{% if use_hipchat %}      hipchat --action sendNotification --room "Marvin Notifications" --messageFormat "html" --colour "gray" --message "test $TESTFILENAME in {{ env_name_clean }} looks <span style="color:#2F962F">OK</span>. Currently; $PASSES passes, $FAILS fails and $NOTRUN_SKIPPED not run.<br>Tests have taken $all_tests_elapsed hours so far. $tests_left tests to go."
+{% endif %}
+{% if use_slack %}      slackmsg "Test $TESTFILENAME looks *OK*.\nCurrently; $PASSES passes, $FAILS fails and $NOTRUN_SKIPPED not run.\nTests have taken $all_tests_elapsed hours so far. $tests_left tests to go." "good"
+{% endif %}
+    fi
+  fi
+}
+
+
+
+
+
 NUMTESTS=`find /marvin/tests/smoke/test_*.py | wc -l`
 run_start_time="$(date -u +%s)"
 counter=1
 PASSES=0
+NOTRUN_SKIPPED=0
+FAILS=0
 # FIXME: make separate list of `dangerous` tests and those that may be run in parallel
 FILES=$(ls /marvin/tests/smoke/test_*py | grep -v test_host_maintenance | grep -v test_hostha_kvm)
 if [ -f /marvin/tests/smoke/test_host_maintenance.py ]; then
@@ -115,44 +175,19 @@ for file in $FILES; do
     all_tests_elapsed="$((($end_time-$run_start_time)/1440))"
     tests_left="$(($NUMTESTS-$counter))"
     echo "$(basename $file): $elapsed seconds" >> $LOGDIR/tests-time.txt
-
-    LASTUPDATEDIR=`ls $LOGDIR/*/ -td | head -n 1`
-    if [[ -s ${LASTUPDATEDIR}failed_plus_exceptions.txt ]]; then
-      echo "test $(basename $file) in {{ env_name_clean }} looks to have errors"
-      {% if use_hipchat %}      hipchat --action sendNotification --room "Marvin Notifications" --messageFormat "html" --colour "gray" --message "test $TESTFILENAME in {{ env_name_clean }} looks to have <span style="color:#FF0000">errors</span>. $PASSES of $counter good so far.<br>Tests have taken $all_tests_elapsed hours so far. $tests_left tests to go."
-{% endif %}
-      {% if use_slack %}      slackmsg "Test $TESTFILENAME looks to have *errors*.\n$PASSES of $counter good so far.\nTests have taken $all_tests_elapsed hours so far. $tests_left tests to go." "warning"
-{% endif %}
-    else
-      PASSES=$((PASSES+1))
-      echo "test $TESTFILENAME in {{ env_name_clean }} looks OK"
-      {% if use_hipchat %}       hipchat --action sendNotification --room "Marvin Notifications" --messageFormat "html" --colour "gray" --message "test $TESTFILENAME in {{ env_name_clean }} looks <span style="color:#2F962F">OK</span>. $PASSES of $counter good so far.<br>Tests have taken $all_tests_elapsed hours so far. $tests_left tests to go."
-{% endif %}
-      {% if use_slack %}      slackmsg "Test $TESTFILENAME looks *OK*.\n$PASSES of $counter good so far.\nTests have taken $all_tests_elapsed hours so far. $tests_left tests to go." "good"
-{% endif %}
-    fi
+    determine_last_test_outcome
     counter=$((counter+1))
 
 done
 
-GOOD=0
-BAD=0
-for file in $LOGDIR/*.xml; do
-  if grep --q 'errors="0" failures="0"' ${file}
-    then
-      GOOD=$((GOOD+1))
-    else
-      BAD=$((BAD+1))
-  fi
-done
-echo "Test completed. $GOOD look ok, $BAD have errors"
+echo "Test completed. $PASSES look ok, $FAILS have errors, $NOTRUN_SKIPPED skipped or failed to run"
 {% if use_hipchat %}hipchat --action sendNotification --room "Marvin Notifications" --messageFormat "html" --message "$$TESTTYPE for <b>{{ env_name_clean }}</b> completed. <br><b>$GOOD</b> look ok, <b>$BAD</b> have errors" --colour "green" --notify
 {% endif %}
-{% if use_slack %}slackmsg "$TESTTYPE completed.\n*$GOOD* looks ok, *$BAD* have errors" "good"
+{% if use_slack %}slackmsg "$TESTTYPE completed.\n$PASSES look ok, $FAILS have errors, $NOTRUN_SKIPPED skipped or failed to run" "good"
 {% endif %}
 
-echo "Smoke tests completed. $GOOD look OK, $BAD have error(s)" >> /marvin/smoketests-summary.txt
-echo "$GOOD look ok, $BAD have errors" > /marvin/test-summary.txt
+echo "$TESTTYPE completed. $PASSES look ok, $FAILS have errors, $NOTRUN_SKIPPED skipped or failed to run" >> /marvin/smoketests-summary.txt
+echo "$PASSES look ok, $FAILS have errors, $NOTRUN_SKIPPED skipped or failed to run" > /marvin/test-summary.txt
 echo "Only failed tests results shown below:" >> /marvin/smoketests-summary.txt
 echo "" >> /marvin/smoketests-summary.txt
 python /marvin/tools/xunit-reader.py $LOGDIR/ >> /marvin/smoketests-summary.txt
